# Test your FastAPI endpoints

### Create a new Grupo
POST http://localhost:8000/grupo
Content-Type: application/json

{
  "nome": "Sr. Vidor"
}

### Mostra todos os grupos salvos no db (DEBUG)
GET http://localhost:8000/grupos

### Create a new Labirinto
POST http://localhost:8000/labirinto
Content-Type: application/json

{
    "vertices": [
        {
            "id": 0,
            "labirintoId": 0,
            "tipo": 1
        },
        {
            "id": 1,
            "labirintoId": 0,
            "tipo": 2
        },
        {
            "id": 2,
            "labirintoId": 0,
            "tipo": 0
        },
        {
            "id": 3,
            "labirintoId": 0,
            "tipo": 0
        },
        {
            "id": 4,
            "labirintoId": 0,
            "tipo": 0
        }
    ],
    "arestas":[
        {
            "origemId": 0,
            "labirintoId": 0,
            "destinoId": 2,
            "peso": 1
        },
        {
            "origemId": 0,
            "labirintoId": 0,
            "destinoId": 3,
            "peso": 1
        },
        {
            "origemId": 1,
            "labirintoId": 0,
            "destinoId": 2,
            "peso": 1
        },
        {
            "origemId": 2,
            "labirintoId": 0,
            "destinoId": 0,
            "peso": 1
        },
        {
            "origemId": 2,
            "labirintoId": 0,
            "destinoId": 1,
            "peso": 1
        },
        {
            "origemId": 3,
            "labirintoId": 0,
            "destinoId": 0,
            "peso": 1
        },
        {
            "origemId": 3,
            "labirintoId": 0,
            "destinoId": 4,
            "peso": 1
        },
        {
            "origemId": 4,
            "labirintoId": 0,
            "destinoId": 3,
            "peso": 1
        }
    ],
    "entrada": 0,
    "dificuldade": "Basiquinho e pequeno"
}

### Get labirintos information for a Grupo
GET http://localhost:8000/labirintos/23042260-6f33-4c19-a063-0633be33bef6

### Create a new WebSocket session
POST http://localhost:8000/generate-websocket/
Content-Type: application/json

{
    "grupo_id": "23042260-6f33-4c19-a063-0633be33bef6",
    "labirinto_id": "0"
}

### Create a new WebSocket session
POST http://localhost:8000/generate-websocket/
Content-Type: application/json

{
    "grupo_id": "23042260-6f33-4c19-a063-0633be33bef6",
    "labirinto_id": "0"
}

### Get all WebSocket sessions (DEBUG)
GET http://localhost:8000/sessoes